main: me.sonny.AnonChat.AnonChat
name: AnonChat
version: 1.2.0
author: Sonny Kim

commands:
  anon:
    description: Hide your nickname on chat.
    
permissions:
  anonchat.use:
    description: Use anon command.
    default: true
    